# This is a configuration file for the NFL Injury Analysis project

# Data paths
data:
  play_data_path: "data/nfl_plays/plays.csv"
  injury_path: "data/injury_reports/nfl_injuries.csv"
  processed_data_path: "data/processed/"
  raw_data_path: "data/raw"
  injury_data_path: "data/injury_reports/nfl_injuries.csv"
  seasons: [2018, 2019, 2020, 2021, 2022]

# Feature lists
features:
  play_features:
    - "game_id"
    - "play_id"
    - "season"
    - "week"
    - "possession_team"
    - "down"
    - "yards_to_go"
    - "yardline_100"
    - "quarter_seconds_remaining"
    - "half_seconds_remaining"
    - "game_seconds_remaining"
    - "game_half"
    - "quarter_end"
    - "play_type"
    - "yards_gained"
    - "shotgun"
    - "no_huddle"
    - "qb_dropback"
    - "qb_kneel"
    - "pass_length"
    - "pass_location"
    - "air_yards"
    - "yards_after_catch"
    - "field_goal_result"
    - "kick_distance"
    - "extra_point_result"
    - "home_timeouts_remaining"
    - "away_timeouts_remaining"
    - "score_differential"
    - "posteam_score"
    - "defteam_score"
    - "posteam_timeouts_remaining"
    - "defteam_timeouts_remaining"
    - "total_home_score"
    - "total_away_score"
    - "play_result"
    
  injury_features:
    - "season"
    - "week"
    - "player_name"
    - "position"
    - "team"
    - "injury"
    - "practice_status"
    - "game_status"
    - "body_region"
    - "injury_severity"
    - "report_date"
    - "season_week"

# Processing parameters
processing:
  fill_missing_values: true
  add_derived_features: true
  remove_duplicates: true
  
# Analysis parameters
analysis:
  target_feature: "injury_severity"
  position_groups:
    QB: ["QB"]
    RB: ["RB", "FB", "HB"]
    WR: ["WR"]
    TE: ["TE"]
    OL: ["T", "G", "C", "OT", "OG"]
    DL: ["DE", "DT", "NT", "DL"]
    LB: ["ILB", "OLB", "MLB", "LB"]
    DB: ["CB", "S", "FS", "SS", "DB"]
    ST: ["K", "P", "LS"]

model:
  random_state: 42
  test_size: 0.2
  features:
    - "play_type"
    - "yards_gained"
    - "down"
    - "game_seconds_remaining"
    - "yardline_100"
    - "score_differential"
    - "surface"
    - "pass"
    - "rush"
    - "sack"
    - "touchdown"
    - "interception"
    - "fumble"
    - "penalty"
    - "play_clock"
    - "quarter"
    - "half_seconds_remaining"
    - "game_half"
    - "posteam_score"
    - "defteam_score"
    - "posteam_timeouts_remaining"
    - "defteam_timeouts_remaining"
    - "home_team"
    - "away_team"
    - "sp"
    - "qtr"
    - "drive"
    - "time_of_day"
    - "stadium"
    - "roof"
    - "start_time"
    - "stadium_id"
    - "game_stadium"
    - "game_date"
    - "week"
    - "season"
    - "game_id"
    - "play_id" 